# Generated by Django 5.2.7 on 2025-11-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
