# Generated by Django 5.2.7 on 2025-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(db_column="tag_name", max_length=100),
        ),
    ]
