# Generated by Django 5.2.7 on 2025-11-06 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_tags_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tags",
            name="id",
        ),
        migrations.AddField(
            model_name="tags",
            name="Tags_id",
            field=models.CharField(
                default=1, max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="tags",
            name="create_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(db_column="tag_name", max_length=100, unique=True),
        ),
    ]
