# Generated by Django 5.2.7 on 2025-11-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_remove_tags_id_tags_tags_id_tags_create_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmodel",
            options={"ordering": ["-pub_time", "name"]},
        ),
        migrations.AlterModelTable(
            name="bookmodel",
            table="book_table",
        ),
    ]
