# Generated by Django 5.2.7 on 2025-11-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_bookmodel_options_alter_bookmodel_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmodel",
            options={"ordering": ["price"]},
        ),
    ]
