# Generated by Django 5.2.7 on 2025-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_bookmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="书名"),
        ),
    ]
