# Generated by Django 5.2.7 on 2025-11-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_tag_article_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="article",
            new_name="tags",
        ),
    ]
