# Generated by Django 5.2.7 on 2025-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_rename_article_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="new_pub_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
